- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Set timezone to Asia/Singapore
  community.general.timezone:
    name: Asia/Singapore

- name: Install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"

- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  ansible.builtin.user:
    name: jignesh
    shell: /bin/bash
    groups: docker
    append: yes

