- name: Create portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    recreate: false
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

# FIREWALL SETUP
- name: Open Portainer port
  ufw:
    state: enabled
    rule: allow
    port: "9000"
    proto: tcp