choco install -Y code
choco install -Y slack
choco install -y zoom
choco install -y firefox
choco install -y ansible
choco install -y wsl2
choco install -y vlc
choco install -y vnc-viewer
choco install -y git